io:
  reader: nii
  path: raw/s0000/ct.nii.gz

preprocess:
  - name: canonicalize
    backend: torch
    target_spacing: 1.0
    # default behavior:
    # 1. min-max normalize scalar volume to [0,1]
    # 2. pad with 0 after normalization
    pad_to_cube: true
    write_vti: true
    vti_path: outputs/s0000/s0000_ct_canonical.vti

render:
  renderer: pv_engine
  path: outputs/s0000/
  executable: pvpython
  num: 64
  w: 800
  h: 800
  vfov: 45
  test_num: 10
  radius_scale: 0.8
  scene_bbox_size: 2.6
  cmaps: Cool to Warm
  band_count: 10
  shading: 0
  opaque_unit: 1.5
  fxaa: 1
  tf_mode: linear
  index: true

sampling:
  name: opacity
  n_points: 50000
  tf_backend: torch
  tf_device: cuda

export:
  writer: ply
  path: outputs/s0000/
