io:
  reader: vti
  path: datasets/supernova_432x432x432_float32x.vti

preprocess:
  - name: tf
    tf_json: "datasets/supernova_432x432x432_float32x.json"
    device: cuda

sampling:
  name: wavelet
  n_points: 50000
  wavelet: haar
  level: 3
  mode: periodic
  device: cuda

export:
  writer: ply
  path: results/supernova_rgba_wavelet.ply
